### ISSUE TITLE
Overflowing u32 extraction silently wraps (or panics in debug mode)

### ISSUE THREAD

**Issue by niklasf** [carllerche/tower-web#100]
Upstream issue: https://github.com/pacman82/atoi-rs/issues/4

atoi does not check for overflows, so this can wrap or panic for release or debug mode respectively: https://github.com/carllerche/tower-web/blob/2fb07a75272a120f0bffc165961b8d5d9c8c5fb1/src/extract/num.rs#L32

Possible solutions:

* `str::from_utf8(...).and_then(...)`
* atoi docs recommend the [`checked`](https://crates.io/crates/checked) crate:
  ```rust
  // By default this will panic in debug or overflow in release builds.
  // assert_eq!(Some(0), atoi::<u8>(b"256")).
  // use the e.g. the `checked` crate to handle overflows gracefully
  ```
* The [`btoi`](https://crates.io/crates/btoi) crate provides a similar API and uses checked arithmetic by default. Full disclosure: I made this fork myself a while ago when I first found that atoi intentionally (https://github.com/pacman82/atoi-rs/issues/1) does not handle overflows.

**Comment by carllerche** [comment]
Using the `checked` crate would be a fine option.
