### ISSUE TITLE
the link for the api doc in README returns a 403 error

### ISSUE THREAD

**Issue by paullgdc** [carllerche/tower-web#121]
When I click on the link to the API documentation in the getting started section of README.md wich is http://rust-doc.s3-website-us-east-1.amazonaws.com/tower-web/v0.3.0/tower_web/ ,
I receive a 403 error with message : 
```
403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: CF8FE2896C1ECF9C
    HostId: f70IzKWwA0u96mvsRWBotYjhBH+ahXMTSiv2b+Bqg0s+4C70t4C7IX8K+OoKJ12PfGZIlgIKpcI=
```

**Comment by shepmaster** [comment]
See also #104. @carllerche is there a better process that can be put in place?

**Comment by carllerche** [comment]
Sigh! If only doc.rs could process the tower-web docs :(

I also am on a backup laptop. It's going to take me a moment to setup my S3 access again.

**Comment by carllerche** [comment]
I uploaded the docs: http://rust-doc.s3-website-us-east-1.amazonaws.com/tower-web/v0.3.0/tower_web/

There probably is a way to hook it up with CI to deploy docs when tagged.

**Comment by paullgdc** [comment]
thanks :)
