### ISSUE TITLE
Request: Allow setting handlebars strict mode

### ISSUE THREAD

**Issue by Phrohdoh** [carllerche/tower-web#133]
https://docs.rs/handlebars/1.0.5/handlebars/struct.Handlebars.html#method.set_strict_mode

**Comment by carllerche** [comment]
You can do this by initializing `Handlebars` with a "registery" (which is just `handlebars::Handlebars`).

http://rust-doc.s3-website-us-east-1.amazonaws.com/tower-web/v0.3.1/tower_web/view/struct.Handlebars.html#method.new_with_registry

**Comment by Phrohdoh** [comment]
Ah yes I looked at that code but, for some reason, thought I'd have to wait til after the tower `Handlebars::new()` to set it.

Sorry for the noise in that case.
