### ISSUE TITLE
Question: Is it possible to enable logging for tower-web without adding logging to my application?

### ISSUE THREAD

**Issue by Phrohdoh** [carllerche/tower-web#137]
As the, unfortunately lengthy, title suggests I'd like to see logs from tower-web (and the deps it brings) without adding logging to my application.

I simply don't have anything useful to log in my code at this stage.

If I must add `env_logger` then so be it, but I'm hoping I can see the logs without adding that dep/code.

**Comment by carllerche** [comment]
Unfortunately, yes. As of now, this is the only way to get it. In the future, this might change.
