### ISSUE TITLE
Bump tower-web-macros version to 0.3.2

### ISSUE THREAD

**Issue by giatruongpho** [carllerche/tower-web#148]
Correct me if I'm wrong but I think you forgot to update the version of tower-web-macros in the latest commit (b4210086ae3256eb33509b9e340a64dc78c0add7).

https://github.com/carllerche/tower-web/blob/b4210086ae3256eb33509b9e340a64dc78c0add7/Cargo.toml#L66
Should be:
`tower-web-macros = { version = "0.3.2", path = "tower-web-macros" }`

**Comment by carllerche** [comment]
Hmm, yeah, looks like it!
