### ISSUE TITLE
Export tower_web::view::Registry

### ISSUE THREAD

**Issue by bryanburgers** [carllerche/tower-web#149]
Should `tower_web::view::Registry` be exported publicly?

Right now, to switch from `Handlebars::new` to `Handlebars::new_with_registry`, the user has to
* add `handlebars = "1.0.3"` to cargo.toml (and potentially keep this in sync with tower-web in the future)
* add `extern handlebars` to the main.rs/lib.rs file
* use `handlebars::Handlebars` instead of the re-named `Registry`

**Comment by carllerche** [comment]
That is fine for now IMO.

The goal of the handlebars integration is to provide basic functionality to prove it out. At some point, it will be extracted into a dedicated crate and can be iterated more there.
