### ISSUE TITLE
Consider mentioning the future plans

### ISSUE THREAD

**Issue by leizzer** [carllerche/tower-web#210]
It will be nice to have the future plan on merging Tower with Warp in the future mentioned in both Readme.
Source: https://medium.com/@carllerche/tower-web-a-new-web-framework-for-rust-e2912856851b

It is already pretty hard to decide which web FW to use in Rust and I think this plan is a really big one to have it scattered over the internet.

Cheers!

**Comment by davyzhang** [comment]
I love this project. Currently, this is the only one that compiles on stable rust and easy to use. A real competitor to the rocket framework which only works on nightly rust.

**Comment by carllerche** [comment]
I opened https://github.com/carllerche/tower-web/issues/218, which covers this question.
