### ISSUE TITLE
#[derive(Extract)] -> error[E0463]: can't find crate for `serde`

### ISSUE THREAD

**Issue by tony-go** [carllerche/tower-web#224]
Hi Guys 🖖 

Im a rust newcomers, so maybe the question is basic but ... 

Is someone knows how I can fix this ? 

<img width="518" alt="Capture d’écran 2020-03-20 à 08 01 43" src="https://user-images.githubusercontent.com/22824417/77142649-12fb3580-6a81-11ea-84d0-001f4b254404.png">

**Comment by tony-go** [comment]
Add serde into cargo.toml seems to fix the problem.

**Comment by lnicola** [comment]
Sorry for the silence here. `tower-web` is somewhat on the back-burner these days. I suggest you take a look at `warp`, another web framework from the author of `hyper`.

**Comment by tony-go** [comment]
Thanks :)
