### ISSUE TITLE
Use attribute syntax instead of magic comments

### ISSUE THREAD

**Issue by sgrif** [carllerche/tower-web#56]
You'd asked me to open an issue to discuss strategy, so here we go. There are basically two options. Ultimately the whole thing is getting passed to a derive, so the simplest option is to not have `impl_web!` spit out the tokens its given unmodified, and instead have `derive_resource!` spit out its input (with the recognized attributes stripped) in addition to what it spits out today.

You mentioned you had a solution which works and messes up error messages, so I'm assuming it's the solution above. The second option would be to run the tokens passed to `impl_web!` through another macro before outputting them. This would be a basic `macro_rules!` macro, which strips out regonized meta items.

Both of these options are pretty simple to implement. Diesel does both in multiple places (depending on whether our macro is fundamentally a `macro_rules!` or procedural macro). Would love to hear more about whether this would somehow affect your error messages.

**Comment by carllerche** [comment]
Yeah, I tried the first route and that basically broke all error messages. I thought of the second strategy but I am not versed in regular macros and it seemed hard.

If this works and maintains good error messages I would be happy to switch to it.

**Comment by carllerche** [comment]
Right now, code errors in the impl_web block are maintained. So you get line numbers and all that. 

When I mutated the actual code in the impl_web block all that was lost.

**Comment by sgrif** [comment]
I don't suppose you have that in the form of a ui test? (e.g. with compiletest-rs)

**Comment by carllerche** [comment]
Unfortunately not

**Comment by sgrif** [comment]
I'd love some guidance here, then. I'm still unclear on what exactly broke in your previous attempts, or how I can verify that I haven't caused the same problem

**Comment by cramertj** [comment]
@sgrif I believe (I could be wrong though) that modifying `TokenStream`s rather than pushing them straight through using the current *stable* proc_macro API will result in the whole thing being stringified, which breaks source location. The updated proc_macro interface fixes this, but it isn't stable yet and so the higher-quality error messages would only be available using nightly. There's some more information on this in the README of the [proc-macro2 crate](https://github.com/alexcrichton/proc-macro2#usage).

**Comment by dtolnay** [comment]
I submitted #59 with a fix that does not disrupt error reporting.

```rust
impl_web! {
    impl JsonResource {
        #[get("/")]
        fn hello_world(&self) -> Result<serde_json::Value, ()> {
            Ok(json!({ "message": "hello world" }))
        }
    }
}
```
