### ISSUE TITLE
Returning different response types from the same handler

### ISSUE THREAD

**Issue by lnicola** [carllerche/tower-web#89]
E.g. I want to return either a `File` or an HTML page. I could probably make do with an enum that implements `Response`, but the `File` and `String` impls have different item types, so it's awkward.

Is there anything `tower-web` can do to make this easier?

**Comment by shepmaster** [comment]
Can you use `Either`?

In my playground fork, I have code like this:

```rust
type Empty = StdStream<stream::Empty<io::Cursor<BytesMut>, io::Error>>;
type MaybeFile = Either<File, Empty>;
type FileResponse = Response<MaybeFile>;
```

```rust
fn index(
    &self,
    if_modified_since: Option<HttpDateTime>,
) -> impl Future<Item = FileResponse, Error = io::Error> + Send
```

**Comment by lnicola** [comment]
That's basically my enum idea, but feels pretty awkward.

**Comment by lnicola** [comment]
Hmm, there's already a `BufStream` impl for `Either<A: BufStream, B: BufStream>`. Maybe there should be a similar one for `Response`?

**Comment by carllerche** [comment]
we can add an `impl Response for Either`.

**Comment by lnicola** [comment]
Yeah, I'll add it, but that leaves the problem of different item types.

Maybe the codegen (macro) could directly support Either with different Response types?

**Comment by lnicola** [comment]
Another idea: make `#[derive(Response)]` work with fields that implement `Response`, e.g.:

```rust
#[derive(Response)]
enum Foo {
    Bar(String),
    Baz(tokio::fs::File),
}
```

**Comment by carllerche** [comment]
We discussed this a bit in Gitter. I really like the idea of deriving `Response` for an enum.

Given that `#[derive(Response)]` has the default behavior of deferring to serde, and serde has an implementation for enums, we can't make the above example "just" work.

I propose we handle it with an attribute. So, this is what it would look like:

```rust
#[derive(Response)]
#[web(either)]
enum Foo {
    Bar(String),
    Baz(tokio::fs::File),
}
```

And this would take an arbitrary enum where each variant's value is a `T: Response` and generate a `Response` impl that defers to the value.

Thoughts @shepmaster @seanmonstar?

On a side note, we should probably think more about the attribute story and make it consistent. Routes use `#[get]` directly, which is nice, but everything else is namespacing it with `web`.

Supposedly, one day `[web::get]` will work, but probably not anytime soon.

**Comment by lnicola** [comment]
As for implementation notes, the generated code should look like this:

```rust
use http;
use tokio::fs::File;
use tower_web::response::{Context, Response, Serializer};
use tower_web::util::tuple::Either2;
use tower_web::util::BufStream;

enum FileOrString {
    File(File),
    String(String),
}

impl Response for FileOrString {
    type Buf = <Self::Body as BufStream>::Item;
    type Body = Either2<<File as Response>::Body, <String as Response>::Body>;

    fn into_http<S: Serializer>(self, context: &Context<S>) -> http::Response<Self::Body> {
        match self {
            FileOrString::File(file) => Either2::A::<File, String>(file).into_http(context),
            FileOrString::String(r) => Either2::B::<File, String>(r).into_http(context),
        }
    }
}
```

**Comment by seanmonstar** [comment]
If asking me about the attribute, I favor `either` over `passthrough`. The english word "either" isn't binary, and at least to me is immediately understandable.

(Does it seem odd at all that `#[web]` is used to alter `derive(Response)`?)
